#!/usr/bin/env mksh
#
# === {{CMD}}
# === Install fonts:
# === Re-logging in or reboot OS
# ===   may be needed to have fonts displayed properly:
PATH="$PATH:$PWD/../my_git/bin"
cd /progs
if [[ -d fonts ]]; then
  cd fonts
  local +x CURRENT="$(my_git describe)"
  echo -n "=== pulling: "
  git pull
  if [[ "$CURRENT" == "$(my_git describe)" ]]; then
    echo "=== Already installed latest."
  else
    ./install.sh
  fi
else
  git clone https://github.com/powerline/fonts
  cd fonts
  ./install.sh
fi
