#!/usr/bin/env mksh
#
# === {{CMD}}
# === Install fonts:
# === Re-logging in or reboot OS
# ===   may be needed to have fonts displayed properly:
cd /progs
if [[ -d fonts ]]; then
  cd fonts
  git pull
else
  git clone https://github.com/powerline/fonts
  cd fonts
fi
./install.sh
